#!/bin/bash

###############
USAGE="
Usage: bash $0 ConfigFile SampleFolder"

if [[ $# -ne 2 ]]; then
    echo "$USAGE"
else
    CONFIGFILE=$1
    OUTPUTLOCATION=$2
fi
###############

###Source config file
echo "Reading config file"
source $CONFIGFILE

###Set variables
VERSIONDOC=${OUTPUTLOCATION}/version.csv
RASPBERRY_RAW_R1=${OUTPUTLOCATION}/raspberry_raw_R1.txt 
RASPBERRY_RAW_R2=${OUTPUTLOCATION}/raspberry_raw_R2.txt 
RASPBERRY_TRIM_R1=${OUTPUTLOCATION}/raspberry_trim_R1.txt
RASPBERRY_TRIM_R2=${OUTPUTLOCATION}/raspberry_trim_R2.txt 
STRAINSEEKER_OUT=${OUTPUTLOCATION}/strainseeker.csv
QUAST_OUT=${OUTPUTLOCATION}/report.tsv
MLST_OUT=${OUTPUTLOCATION}/mlst.tab
KLEBORATE_OUT=${OUTPUTLOCATION}/kleborate.tab
ABRICATE_CARD=${OUTPUTLOCATION}/abricate_card.tab
ABRICATE_PLASMID=${OUTPUTLOCATION}/abricate_plasmid.tab
ABRICATE_INHOUSE=${OUTPUTLOCATION}/abricate_inhouse.tab
OUTPUT_XML_TEMP=${OUTPUTLOCATION}/${OUTPUTLOCATION%/}_${DATE}_CRACKLE_v${VERSION}_temp.xml
OUTPUT_XML=${OUTPUTLOCATION}/${OUTPUTLOCATION%/}_${DATE}_CRACKLE_v${VERSION}.xml

###R program to generate xml files
echo "Generating XML file"
echo "Command used: Rscript $XML_GENERATOR_PATH $SITE $LIBRARY_PREP $DATE $VERSION $VERSIONDOC $RASPBERRY_RAW_R1 $RASPBERRY_RAW_R2 $RASPBERRY_TRIM_R1 $RASPBERRY_TRIM_R2 $QUAST_OUT $STRAINSEEKER_OUT $MLST_OUT $KLEBORATE_OUT $ABRICATE_CARD $ABRICATE_PLASMID $ABRICATE_INHOUSE $CARDLIST $PLASMIDLIST $INHOUSELIST $OUTPUT_XML_TEMP"
Rscript $XML_GENERATOR_PATH $SITE $LIBRARY_PREP $DATE $VERSION $VERSIONDOC $RASPBERRY_RAW_R1 $RASPBERRY_RAW_R2 $RASPBERRY_TRIM_R1 $RASPBERRY_TRIM_R2 $QUAST_OUT $STRAINSEEKER_OUT $MLST_OUT $KLEBORATE_OUT $ABRICATE_CARD $ABRICATE_PLASMID $ABRICATE_INHOUSE $CARDLIST $PLASMIDLIST $INHOUSELIST $OUTPUT_XML_TEMP
#Takes flat xml file and restores tree structure
xmllint --format $OUTPUT_XML_TEMP > $OUTPUT_XML

echo "Cleaning up"
rm $OUTPUT_XML_TEMP

echo "All done"
